Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      AcrImageArtifactRelation:
        # 相应的，ros模板中也需要采用该伪参数
        '{{ computenest::acrimage::LYH-RAIN_metabase-dockerfile }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        # 未选择部署地域则采用 []
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: AcrImage
    # 采用与image_name相同的ArtifactName
    ArtifactName: lyh-rain_metabase-dockerfile
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Private
AcrImageBuilder:
  AcrImage_1:
    # dockerfile路径
    DockerFilePath: Dockerfile
    # 采用与image_name相同的repoName
    RepoName: lyh-rain_metabase-dockerfile
    Tag: latest
    DockerBuildArgs: [{'ArgumentValue': 'latest', 'ArgumentName': 'VERSION'}]